import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

import { IsMobileProvider } from './contexts/mobile-context';
import { LanguageProvider } from './contexts/language-context';
import { BasketProvider } from './contexts/basket-context';
import { IconsProvider } from './contexts/icons-context';
import Navbar from './components/navbar/navbar';
import PageContent from './components/page-content/page-content';
import Basket from './components/basket/basket';
import Footer from './components/footer/footer';

import './globals.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IsMobileProvider>
          <LanguageProvider>
            <IconsProvider>
              <BasketProvider>
                <Navbar/>
                <PageContent>
                  {children}
                </PageContent>
                <Basket/>
                <Footer/>
              </BasketProvider>
            </IconsProvider>
          </LanguageProvider>
        </IsMobileProvider>
      </body>
    </html>
  );
}
