import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import React from 'react';

import { IsMobileProvider } from './contexts/mobile-context';
import { LanguageProvider } from './contexts/language-context';
import Navbar from './components/navbar/navbar';
import Footer from './components/footer/footer';

import './globals.scss';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IsMobileProvider>
          <LanguageProvider>
            <Navbar/>
            {children}
            <Footer/>
          </LanguageProvider>
        </IsMobileProvider>
      </body>
    </html>
  );
}
